version: '3.8'
services:
  db:
    image: postgres
    restart: always
    env_file: .env
    ports:
      - '5433:5432'
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      # Inicialize database creating tables
      - ./sql/init_tables.sql:/docker-entrypoint-initdb.d/sql/init_tables.sql
      # Create triggers
      - ./sql/create_triggers.sql:/docker-entrypoint.initdb.d/sql/create_triggers.sql
      # Shared folder 
      - app-data:/tmp:z

  service:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    depends_on:
      - db
    networks: 
      - default
    ports:
      - 8088:8088
    volumes:
      - app-data:/tmp:z
volumes:
  postgres-data:
  app-data: